const express = require("express")
const app = express()
const userRoutes = require("../prod/chatapp/auth-service/routes/userRoutes.js")
const corsConfiguration = require("../prod/chatapp/auth-service/config/corsConfig.js")
const cors = require("cors")
const connectDB = require("../prod/chatapp/auth-service/config/dbConfig.js")
const dotenv = require('dotenv')
dotenv.config()
connectDB()
app.use(express.json()) 
app.use(corsConfiguration())
app.use("/api/v1/users", userRoutes)

app.listen(8080,()=> console.log("auth serverice started on 8080 port"))