const express = require("express")
const app = express()
const userRoutes = require("./routes/userRoutes.js")
const corsConfiguration = require("./config/corsConfig.js")
const cors = require("cors")
const connectDB = require("./config/dbConfig.js")
const dotenv = require('dotenv')
dotenv.config()

const port = process.env.PORT || 8000
connectDB() 
app.use(corsConfiguration())
app.use(express.json()) 
app.use("/api/v1/users", userRoutes)
app.all("*", (req,res)=>res.send("Invalid Endpoint triggered"))
app.listen(port,()=> console.log(`auth serverice started on ${port} port`))